---
version: '3.7'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8050:80 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: shopon
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wpdb
    secrets:
      - db_password
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: shopon
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8282:80
    environment:
      MYSQL_USER: ranjit
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
secrets:
   db_password:
     file: set_db_password.txt
   db_root_password:
     file: set_db_root_password.txt
volumes:
  wordpress:
  db:
